# Generated by Django 4.1 on 2022-08-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boocodingexercise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='DislikedBy',
            field=models.CharField(default='', max_length=102400),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='LikedBy',
            field=models.CharField(default='', max_length=102400),
        ),
    ]
